const citiesInIndia = [
    { value: 'Mumbai', label: 'Mumbai' },
    { value: 'Delhi', label: 'Delhi' },
    { value: 'Bangalore', label: 'Bangalore' },
    { value: 'Shahjahanpur', label: 'Shahjahanpur' },
    { value: 'Pilibhit', label: 'Pilibhit' },
    { value: 'Raebareli', label: 'Raebareli' },
    { value: 'Lucknow', label: 'Lucknow' },
    { value: 'Prayagraj', label: 'Prayagraj' },
    { value: 'Unnao', label: 'Unnao' },
    { value: 'Rampur', label: 'Rampur' },
    { value: 'Varanasi', label: 'Varanasi' },
    { value: 'Agra', label: 'Agra' },
    { value: 'Bareilly', label: 'Bareilly' },
    { value: 'Deoria', label: 'Deoria' },
    { value: 'Mau', label: 'Mau' },
    { value: 'Basti', label: 'Basti' },
    { value: 'Etah', label: 'Etah' },
    { value: 'Sultanpur', label: 'Sultanpur' },
    { value: 'Banda', label: 'Banda' },
    { value: 'Jhansi', label: 'Jhansi' },
    { value: 'Ghaziabad', label: 'Ghaziabad' },
    { value: 'Mathura', label: 'Mathura' },
    { value: 'Orai', label: 'Orai' },
    { value: 'Gorakhpur', label: 'Gorakhpur' },
    { value: 'Noida', label: 'Noida' },
    { value: 'Kanpur', label: 'Kanpur' },
    { value: 'Fatehpur', label: 'Fatehpur' },
    { value: 'Budaun', label: 'Budaun' },
    { value: 'Bulandshahr', label: 'Bulandshahr' },
    { value: 'Muzaffarnagar', label: 'Muzaffarnagar' },
    { value: 'Jaunpur', label: 'Jaunpur' },
    { value: 'Mainpuri', label: 'Mainpuri' },
    { value: 'Akbarpur', label: 'Akbarpur' },
    { value: 'Amroha', label: 'Amroha' },
    { value: 'Sambhal', label: 'Sambhal' },
    { value: 'Ghazipur', label: 'Ghazipur' },
    { value: 'Gonda', label: 'Gonda' },
    { value: 'Lalitpur', label: 'Lalitpur' },
    { value: 'Hardoi', label: 'Hardoi' },
    { value: 'Auraiya', label: 'Auraiya' },
    { value: 'Baghpat', label: 'Baghpat' },
    { value: 'Maharajganj', label: 'Maharajganj' },
    { value: 'Chandauli', label: 'Chandauli' },
    { value: 'Khurja', label: 'Khurja' },
    { value: 'Baraut', label: 'Baraut' },
    { value: 'Mirzapur', label: 'Mirzapur' },
    { value: 'Padrauna', label: 'Padrauna' },
    { value: 'Robertsganj', label: 'Robertsganj' },
    { value: 'Khalilabad', label: 'Khalilabad' },
    { value: 'Jalaun', label: 'Jalaun' }
  ];
  
  export default citiesInIndia;
  